org: jorgemelgarejo
service: api-students

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  role: arn:aws:iam::767397712076:role/LabRole
  stage: ${opt:stage, 'dev'}

package:
  individually: true

functions:
  CreateStudent:
    handler: Lambda_CreateStudent.lambda_handler
    memorySize: 512
    timeout: 30
    environment:
      VALIDATE_FUNCTION_NAME: ${self:custom.validateTokenFunction}
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: students
          method: post
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }

  GetStudent:
    handler: Lambda_Get_Student.lambda_handler
    memorySize: 512
    timeout: 30
    environment:
      VALIDATE_FUNCTION_NAME: ${self:custom.validateTokenFunction}
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: students
          method: get
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  }
                }

  UpdateStudent:
    handler: Lambda_Update_Student.lambda_handler
    memorySize: 512
    timeout: 30
    environment:
      VALIDATE_FUNCTION_NAME: ${self:custom.validateTokenFunction}
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: students
          method: put
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  },
                  "body": $input.body
                }

  DeleteStudent:
    handler: Lambda_Delete_Student.lambda_handler
    memorySize: 512
    timeout: 30
    environment:
      VALIDATE_FUNCTION_NAME: ${self:custom.validateTokenFunction}
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: students
          method: delete
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "method": "$context.httpMethod",
                  "path": "$context.path",
                  "headers": {
                    "Authorization": "$input.params('Authorization')"
                  }
                }

custom:
  validateTokenFunction: api-security-${self:provider.stage}-ValidateAccessToken
