org: jorgemelgarejo
service: rewards-api

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::767397712076:role/LabRole
  environment:
    REWARDS_TABLE: ${sls:stage}-t_rewards
    TOKENS_TABLE: ${sls:stage}-t_access_tokens
    VALIDATE_FUNCTION_NAME: validateAccessToken-${sls:stage}

functions:
  createReward:
    handler: Lambda_CreateReward.handler
    events:
      - http:
          path: /reward/create
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    RewardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.REWARDS_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: reward_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: reward_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TOKENS_TABLE}
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST